package ss7_abstract_class_and_interface.practice.animal_class_and_interface_edible.Fruit;

import ss7_abstract_class_and_interface.practice.animal_class_and_interface_edible.Ediable.Edible;

public abstract class Fruit implements Edible {}
